[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".vim/bundle/ale"]
    type = "archive"
    url = "https://github.com/dense-analysis/ale/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".vim/bundle/tabular"]
    type = "archive"
    url = "https://github.com/godlygeek/tabular/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".vim/bundle/vim-flake8"]
    type = "archive"
    url = "https://github.com/nvie/vim-flake8/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".vim/bundle/vim-fugitive"]
    type = "archive"
    url = "https://github.com/tpope/vim-fugitive/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".vim/bundle/vim-gitgutter"]
    type = "archive"
    url = "https://github.com/airblade/vim-gitgutter/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
